/*
 * generated by Xtext
 */
package org.eclipse.ocl.examples.xtext.oclstdlib.ui;

import org.eclipse.ocl.examples.xtext.essentialocl.ui.model.BaseDocument;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.common.types.access.jdt.IJavaProjectProvider;
import org.eclipse.xtext.ui.editor.model.XtextDocument;

/**
 * Use this class to register components to be used within the IDE.
 */
public class OCLstdlibUiModule extends AbstractOCLstdlibUiModule
{
	public OCLstdlibUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public Class<? extends IJavaProjectProvider> bindIJavaProjectProvider() {
		return NonXtextResourceSetBasedProjectProvider.class;
	}

	public Class<? extends XtextDocument> bindXtextDocument() {
		return BaseDocument.class;
	}
}
