/*
 * generated by Xtext
 */
package org.eclipse.ocl.examples.xtext.oclstdlib.ui;

import org.eclipse.ocl.examples.xtext.oclstdlib.ui.refactoring.OCLstdlibReferenceUpdater;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.common.types.access.jdt.IJavaProjectProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class OCLstdlibUiModule extends AbstractOCLstdlibUiModule
{
	public static final String EDITOR_ID = "org.eclipse.ocl.examples.xtext.oclstdlib.OCLstdlib";

	public OCLstdlibUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
//	@SuppressWarnings("restriction")
//	public Class<? extends org.eclipse.xtext.ui.refactoring.IRenameStrategy.Provider> bindIRenameStrategy$Provider() {
//		return OCLstdlibRenameStrategy.Provider.class;
//	}
	
	@SuppressWarnings("restriction")
	public Class<? extends org.eclipse.xtext.ui.refactoring.IReferenceUpdater> bindIReferenceUpdater() {
		return OCLstdlibReferenceUpdater.class;
	}
	
	@Override
	public Class<? extends IJavaProjectProvider> bindIJavaProjectProvider() {
		return NonXtextResourceSetBasedProjectProvider.class;
	}
}
