/*
 * generated by Xtext
 */
package org.eclipse.ocl.examples.xtext.oclinecore.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.ocl.examples.xtext.oclinecore.ui.internal.OCLinEcoreActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OCLinEcoreExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return OCLinEcoreActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return OCLinEcoreActivator.getInstance().getInjector(OCLinEcoreActivator.ORG_ECLIPSE_OCL_EXAMPLES_XTEXT_OCLINECORE_OCLINECORE);
	}
	
}
