/*
 * generated by Xtext
 */
package org.eclipse.ocl.examples.xtext.markup.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MarkupExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.eclipse.ocl.examples.xtext.markup.ui.internal.MarkupActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.eclipse.ocl.examples.xtext.markup.ui.internal.MarkupActivator.getInstance().getInjector("org.eclipse.ocl.examples.xtext.markup.Markup");
	}
	
}
